//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string NetworkOperator { get; set; }
        public string MSISDN { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Timestamped { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
    }
}
