//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDSeries
    {
        public long ID { get; set; }
        public string Prefix { get; set; }
        public Nullable<long> MinValue { get; set; }
        public long NextValue { get; set; }
        public Nullable<long> MaxValue { get; set; }
        public string Suffix { get; set; }
        public string Description { get; set; }
        public int Increment { get; set; }
    }
}
