//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        public int RequestId { get; set; }
        public string MSISDN { get; set; }
        public System.Guid TransactionId { get; set; }
        public string ClientIp { get; set; }
        public string SourceChannel { get; set; }
        public bool HeaderEnabled { get; set; }
        public int ServiceHeaderId { get; set; }
        public System.DateTime Timestamped { get; set; }
    }
}
