//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceResponses
    {
        public int ResponseId { get; set; }
        public int RequestId { get; set; }
        public string StatusCode { get; set; }
        public string Description { get; set; }
        public System.DateTime Timestamped { get; set; }
    }
}
